apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: pg-nightly-replica-kill
  namespace: chaos-mesh
spec:
  schedule: "0 1 * * *"
  historyLimit: 3
  concurrencyPolicy: "Forbid"
  type: "PodChaos"
  podChaos:
    action: pod-kill
    mode: one
    selector:
      namespaces:
        - demo
      labelSelectors:
        "app.kubernetes.io/instance": "pg-ha-cluster"
        "kubedb.com/role": "standby"
