apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: pg-replication-latency
  namespace: chaos-mesh
spec:
  action: latency
  mode: one
  selector:
    namespaces:
      - demo
    labelSelectors:
      "app.kubernetes.io/instance": "pg-ha-cluster"
      "kubedb.com/role": "primary"
  target:
    mode: all
    selector:
      namespaces:
        - demo
      labelSelectors:
        "app.kubernetes.io/instance": "pg-ha-cluster"
        "kubedb.com/role": "standby"
  latency:
    latency: "150ms"
    jitter: "50ms"
  duration: "2m"
  direction: to
