apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: pg-coordinator-network-disruption
  namespace: chaos-mesh
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - demo
    labelSelectors:
      "app.kubernetes.io/instance": "pg-ha-cluster"
  delay:
    latency: "250ms"
    jitter: "200ms"
    correlation: "25"
  duration: "5m"

