apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: pg-coordinator-packet-loss
  namespace: chaos-mesh
spec:
  action: loss
  mode: all
  selector:
    namespaces:
      - demo
    labelSelectors:
      "app.kubernetes.io/instance": "pg-ha-cluster"
  target:
    mode: all
    selector:
      namespaces:
        - demo
      labelSelectors:
        "app.kubernetes.io/instance": "pg-ha-cluster"
  loss:
    loss: "30"
    correlation: "25"
  direction: both
  targetPort: "2379,2380"
  duration: "5m"
