apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: pg-primary-cpu-stress
  namespace: chaos-mesh
spec:
  mode: one
  selector:
    namespaces:
      - demo
    labelSelectors:
      "app.kubernetes.io/instance": "pg-ha-cluster"
      "kubedb.com/role": "primary"
  stressors:
    cpu:
      workers: 2
      load: 80
  duration: "5m"
