apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: pg-replica-memory-stress
  namespace: chaos-mesh
spec:
  mode: one
  selector:
    namespaces:
      - demo
    labelSelectors:
      "app.kubernetes.io/instance": "pg-ha-cluster"
      "kubedb.com/role": "standby"
  stressors:
    memory:
      workers: 1
      size: "512MB"
  duration: "2m"
