apiVersion: kubedb.com/v1
kind: Postgres
metadata:
  name: pg-ha-cluster
  namespace: demo
spec:
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        port: 56790
        resources:
          requests:
            cpu: 200m
            memory: 250Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 70
          runAsNonRoot: true
          runAsUser: 70
          seccompProfile:
            type: RuntimeDefault
      serviceMonitor:
        interval: 10s
        labels:
          release: prometheus
  clientAuthMode: "cert"
  sslMode: "verify-full"
  allowedSchemas:
    namespaces:
      from: Same
  authSecret:
    activeFrom: "2025-10-16T04:56:36Z"
    apiGroup: ""
    name: pg-ha-cluster-auth
  autoOps: {}
  deletionPolicy: Halt
  halted: false
  healthChecker:
    failureThreshold: 1
    periodSeconds: 10
    timeoutSeconds: 10
  leaderElection:
    electionTick: 10
    heartbeatTick: 1
    maximumLagBeforeFailover: 67108864
    period: 300ms
    transferLeadershipInterval: 1s
    transferLeadershipTimeout: 1m0s
  podTemplate:
    controller: {}
    metadata: {}
    spec:
      containers:
      - name: postgres
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 70
          runAsNonRoot: true
          runAsUser: 70
          seccompProfile:
            type: RuntimeDefault
      - name: pg-coordinator
        args:
          - --v=5
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 70
          runAsNonRoot: true
          runAsUser: 70
          seccompProfile:
            type: RuntimeDefault
      initContainers:
      - name: postgres-init-container
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 70
          runAsNonRoot: true
          runAsUser: 70
          seccompProfile:
            type: RuntimeDefault
      podPlacementPolicy:
        name: default
      securityContext:
        fsGroup: 70
        runAsGroup: 70
        runAsUser: 70
      serviceAccountName: pg-ha-cluster
  replicas: 3
  replication:
    walKeepSize: 3000
    walLimitPolicy: WALKeepSize
  standbyMode: Hot
  tls:
    issuerRef:
      name: pg-issuer
      kind: Issuer
      apiGroup: cert-manager.io
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 3Gi
  storageType: Durable
  version: "16.4"
